### PR TITLE
Changes headers to sentence case

### PR DESCRIPTION
**Pull request by kevinkq**
## Summary of the changes / Why this is an improvement

Changes headers from title case to sentence case.

## Checklist

 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Comment by mkleen** [comment]
I modified the travis build and removed the nightly build, then this should work now.

**Comment by mechanomi** [comment]
@mkleen how come we're removing the nightly build instead of fixing it? or is this a temporary measure?

**Comment by seut** [comment]
@mechanomi see commit message https://github.com/crate/crate-pdo/pull/96

**Comment by mkleen** [comment]
retest this please

**Comment by mechanomi** [comment]
@seut takk!

**Comment by mechanomi** [comment]
retest this please

**Comment by mechanomi** [comment]
hmm "retest this please" didn't seem to trigger the CI

**Comment by seut** [comment]
@mechanomi you have to rebase anyway to get the travis config changes in 😉

**Pull request merged**
