### PR TITLE
Modernize repository and CI

### PR DESCRIPTION
**Pull request by amotl**
Hi there,

like already done on `crate-dbal`, this modernizes the repository and the CI configuration.

- Bump to HTTP client "guzzle^7.2"
- Replace Travis CI by GitHub Actions
- Rename default branch to "main"
- Update Scrutinizer configuration
- Update documentation
- Update development dependencies
- Run code style checks

With kind regards,
Andreas.

### CODE REVIEW

**Comment by amotl** [comment]
Please note [`.github/workflows/tests.yml`](https://github.com/crate/crate-pdo/blob/bc1d39fe5f348da1dce098c57991ed463abee2d0/.github/workflows/tests.yml) is a perfect blueprint how to run CrateDB on GitHub Actions with a custom configuration, specifically here it is about enabling SSL where some other files (keys and certificates) have to be provisioned to the container beforehand.

In order to accomplish this, we don't use GitHub Actions' native `services` configuration but leverage `docker-compose` instead. The accompanied [`docker-compose.yml`](https://github.com/crate/crate-pdo/blob/bc1d39fe5f348da1dce098c57991ed463abee2d0/test/provisioning/docker-compose.yml) makes use of health checks as well as a sidecar container to wait for the service to be available properly before handing over to the next job steps, even when starting Docker Compose in `--detach`ed mode.

**Comment by amotl** [comment]
Hi.

I wanted to share with you that, while revamping the `crate-pdo` driver and now running it against CrateDB Nightly on GitHub Actions, the process currently experiences a (hopefully) minor hiccup on PHP7.4 only (works on PHP7.2 and PHP7.3 though). I will discuss that with @seut, so JFYI and sorry for the noise.

- Job failure: https://github.com/crate/crate-pdo/runs/1962329131?check_suite_focus=true
- Code in question: https://github.com/crate/crate-pdo/blob/1.1.0/test/CrateIntegrationTest/PDO/PDOStatementTest.php#L335-L345
- Thoughts: `Trying to access array offset on value of type bool` indicates `$statement->fetchAll(PDO::FETCH_NAMED)` returns false, probably from https://github.com/crate/crate-pdo/blob/1.1.0/src/Crate/PDO/PDOStatement.php#L235 or other places in that function.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Running this on my workstation with `-Cstats.enabled=true` reveals from `sys.jobs_log` (even on PHP7.2) that the statement `INSERT INTO test_table (name) VALUES (?)` errors with
```
Column `id` is required but is missing from the insert statement.
```
So, the problem might not be related to the `NULL` parameter binding at all. However, this test case does not croak on PHP7.2.

**Comment by amotl** [comment]
Inspired by [1], I decided to ask PDO to throw exceptions like
```
PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
```

And indeed, the statement error revealed through `sys.jobs_log` is now a real error.

```sh
$ composer run -- test --filter "testNullParamBinding"

There was 1 error:

1) CrateIntegrationTest\PDO\PDOStatementTest::testNullParamBinding
Crate\PDO\Exception\PDOException: SQLParseException[Column `id` is required but is missing from the insert statement]

/Users/amo/dev/crate/sources/crate-pdo/src/Crate/PDO/PDO.php:129
/Users/amo/dev/crate/sources/crate-pdo/src/Crate/PDO/PDOStatement.php:211
/Users/amo/dev/crate/sources/crate-pdo/src/Crate/PDO/PDOStatement.php:211
/Users/amo/dev/crate/sources/crate-pdo/test/CrateIntegrationTest/PDO/PDOStatementTest.php:340
```

[1] https://bugs.php.net/bug.php?id=65825

**Comment by amotl** [comment]
It turns out the test was just plain wrong as it didn't issue a `SELECT ...` statement before comparing the outcome. The situation has been improved by adding appropriate tests like `testInsertNull`, `testInvalidInsert`, `testNullParamBinding` and `testInvalidInsertWithNullParamBinding` with 1af29dd.

**Review by seut — APPROVED** [review]
👍

**Pull request merged**
