### PR TITLE
fix: composer authoritative

### PR DESCRIPTION
**Pull request by JulianMar**
## Summary of the changes / Why this is an improvement
* make it possible to use composer [authoritative classmap](https://getcomposer.org/doc/articles/autoloader-optimization.md#optimization-level-2-a-authoritative-class-maps)
* extending a class based on php version is calculated at dump-autoload

## Checklist

 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Comment by JulianMar** [comment]
Okay I see there is a issue with the code style.
It's not allowed to define more than one Interface/Trait/Class in one file, so I am not sure if I should just add a ignore.

What do you guys think?

**Comment by amotl** [comment]
Hi Julian,

if your patch will not impact any runtime behavior, I believe it is fine to add `// phpcs:disable` to all of the referenced "dispatcher" files formerly containing the `class_alias()` commands (`PDOImplementation.php`, `PDOStatementImplementation.php`, `PDOInterface.php`), in order to satisfy the linter.

With kind regards,
Andreas.

**Comment by JulianMar** [comment]
Hey,

sounds good! The change doesn't introduce any breaking change, so I just added the ignore comment

thanks

**Comment by amotl** [comment]
Thanks a stack!

**Comment by amotl** [comment]
Your improvement is available as `crate/crate-pdo:2.1.3`, see https://packagist.org/packages/crate/crate-pdo.

**Pull request merged**
